### ISSUE TITLE
show running screen cpu and ram value

### ISSUE THREAD

**Issue by russh3l** [scaidermern/script-snippets#2]
hello, 

is it possible run this with screen name show running screens cpu and ram without user? 

thanks

**Comment by scaidermern** [comment]
What is "screen" in this context? Can you show an example output?

**Comment by russh3l** [comment]
Im running game servers with one user ... example "screen -ls" commands output ;

>         8918.gameserver52     (11/01/2018 02:06:40 PM)        (Detached)
>         8992.gameserver117   (11/01/2018 05:53:10 AM)        (Detached)

i want to use this with running screen names example; gameserver52 or gameserver117

**Comment by scaidermern** [comment]
Sorry, this is out of the scope of my scripts. You can fork the repository and modify them yourself if you like.
